---
language: node_js
node_js:
- 0.10
before_script:
  - npm install -g grunt-cli
  - git submodule update --init --recursive
env:
  global:
  - secure: ! 'Pu2W4rZhaZiJUay75kkoCGObCR0pzolGDZjTQahjzcUc+oTutoyWJMHVQJ/uO3mdo7aBxJWaRFPGdn3gQFGP7bGuGasBA4EnH/iJE1mYMh3jlxJsYR4B4TWv8U9mwqJleGWb1pQkQa8++uewXYIYH5ex70VE1nsgfq9t+0U5cIc='
  - secure: ! 'IczxL/pV/StvTzM9PiQmqj5JqyQapVBFthda5JdALgl9/y65n7YhtOFVNmD1xL06HgtIBKiL62qlW0T+Jl4RAP/SbPOsDLKVgxrZJDQ77sL7arMQyPjSlb88S7V4rbCioqY9cEcyg8eRaldScCsmuAlprmgifcVJtd2aS8+CYi8='
